# .github/workflows/pypi.yml
jobs:
  pypi-publish:
    name: CD_DM
    runs-on: Windows, linux, Mac
    environment:
      name: pypi
      url: https://codedocta.com
    permissions:
      id-token: pypi-AgEIcHlwaS5vcmcCJDI4YzM1ZTAwLWIxZGEtNGIwMy1hNDlmLTczNWJmM2Y5NTc2YgACKlszLCI3MmFlNTNmOS1iMmEzLTRmYWYtYjg0MS1kNDkwYTQ2YmJhMTAiXQAABiAmprOmZ0scxtR8p5pm50ln2zzsazSBlrEcv0iNKopSdw
    steps:
    # retrieve your distributions here

    - name: Publish package distributions to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1
