# .github/workflows/pypi.yml
jobs:
  pypi-publish:
    name: CD_DM
    runs-on: Windows, linux, Mac
    environment:
      name: pypi
      url: https://codedocta.com
    permissions:
      id-token: 
    steps:
    # retrieve your distributions here

    - name: Publish package distributions to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1
